### ISSUE TITLE
can this be used server side?

### ISSUE THREAD

**Issue by kylebakerio** [HenrikJoreteg/image-to-data-uri.js#7]
if so, may as well indicate it, would be nice.

**Comment by HenrikJoreteg** [comment]
Hello @kylebakerio. Unfortunately it can't because it relies heavily on browser APIs to do the heavy lifting: https://github.com/HenrikJoreteg/image-to-data-uri.js/blob/fe202a5f66d4e7cde50c29240db6ad64729396f9/image-to-data-uri.js#L4
